load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "sample_files",
    srcs = ["src/sample.tao"],
    visibility = ["//visibility:public"],
)


rust_binary(
    name = "main",
    srcs = ["src/main.rs", "src/scanner.rs"],
    compile_data = [":sample_files"],
    deps = [
        "@crates//:ariadne",
    ],
)

rust_library(
    name = "scanner",
    srcs = ["src/scanner.rs"],
    deps = [
        "@crates//:ariadne"
    ]
)

rust_library(
    name = "parser",
    srcs = ["src/parser.rs"],
    deps = [
        ":scanner",
    ]
)

rust_test(
    name = "scanner_test",
    crate = ":scanner"
)

rust_test(
    name = "parser_test",
    crate = ":parser"
)
