load("@rules_rust//rust:defs.bzl", "rust_binary", "rustfmt_test", "rust_library", "rust_test")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "main",
    srcs = ["src/main.rs"],
    deps = [
        ":compiler",
        ":memory_manager",
        ":virtual_machine",
        ":scanner",
        "@crates//:ariadne",
        "@crates//:serde_json",
    ],
    crate_features = [
        "stress_gc"
    ]
)

rust_library(
    name = "scanner",
    srcs = ["src/scanner.rs"],
    deps = [
        "@crates//:ariadne",
    ],
    crate_features = [
        "stress_gc"
    ]
)

rust_library(
    name = "parser",
    srcs = ["src/parser.rs"],
    deps = [
        ":scanner",
    ],
    crate_features = [
        "stress_gc"
    ]
)

rust_library(
    name = "chunk",
    srcs = ["src/chunk.rs"],
    deps = [
        "@crates//:ariadne",
        ":scanner",
        "@crates//:slotmap"
    ],
    crate_features = [
        "stress_gc"
    ]
)

rust_library(
    name = "virtual_machine",
    srcs = ["src/virtual_machine.rs"],
    deps = [
        ":chunk",
        ":compiler",
        ":coverage",
        ":memory_manager",
        ":scanner",
        ":native",
        ":serialized_chunk",
        "@crates//:serde_json",
        "@crates//:serde_yaml",
        "@crates//:slotmap"
    ],
    crate_features = [
        "stress_gc",
    ]
)

rust_library(
    name = "native",
    srcs = ["src/native.rs"],
    deps = [
        ":chunk",
        ":memory_manager",
        "@crates//:md5",
        "@crates//:sha2",
        "@crates//:sha1",
        "@crates//:sha3",
    ],
    crate_features = [
        "stress_gc",
    ]
)

rust_library(
    name = "memory_manager",
    srcs = ["src/memory_manager.rs"],
    deps = [
        "@crates//:slotmap",
        ":chunk",
    ],
    crate_features = [
        "stress_gc",
    ]
)

rust_library(
    name = "compiler",
    srcs = ["src/compiler.rs", "src/compiler_integration_test.rs"],
    deps = [
        ":chunk",
        ":scanner",
        ":parser",
        ":memory_manager",
    ],
    crate_features = [
        "stress_gc"
    ]
)

rust_library(
    name = "serialized_chunk",
    srcs = ["src/serialized_chunk.rs"],
    deps = [
        ":chunk",
        ":memory_manager",
        "@crates//:fory",
        "@crates//:fory-core",
        "@crates//:slotmap",
    ],
    proc_macro_deps = [
        "@crates//:fory-derive",
    ],
    crate_features = [
        "stress_gc"
    ]
)

rust_library(
    name = "coverage",
    srcs = ["src/coverage.rs"],
)

rust_library(
    name = "test_reporter",
    srcs = ["src/test_reporter.rs"],
)

rust_binary(
    name = "jsonnet_compiler",
    srcs = ["src/jsonnet_compiler.rs"],
    deps = [
        ":compiler",
        ":memory_manager",
        ":scanner",
        ":serialized_chunk",
        ":chunk",
    ],
    crate_features = [
        "stress_gc"
    ]
)

rust_test(
    name = "scanner_test",
    crate = ":scanner"
)

rust_test(
    name = "parser_test",
    crate = ":parser"
)

rust_test(
    name = "chunk_test",
    crate = ":chunk"
)

rust_test(
    name = "virtual_machine_test",
    crate = ":virtual_machine"
)

rust_test(
    name = "compiler_test",
    crate = ":compiler"
)

rust_test(
    name = "memory_manager_test",
    crate = ":memory_manager",
)

rust_test(
    name = "serialized_chunk_test",
    crate = ":serialized_chunk",
)

rust_test(
    name = "coverage_test",
    crate = ":coverage"
)

rust_test(
    name = "test_reporter_test",
    crate = ":test_reporter"
)

rustfmt_test(
    name = "format_test",
    targets = [
        ":compiler",
        ":virtual_machine",
        ":scanner",
        ":parser",
        ":chunk",
        ":memory_manager",
        ":native",
        ":serialized_chunk",
        ":jsonnet_compiler",
        ":coverage",
        ":test_reporter",
    ],
)


