"""sdreynolds/RapidJsonnet build of Jsonnet using a bytecode interpreter"""

module(name = "rapidjsonnet")

bazel_dep(name = "rules_rust", version = "0.62.0")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(edition = "2024")
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")

crate.spec(
    package = "ariadne",
    features = ["auto-color"],
    version = "0.5.1"
)

crate.spec(
    package = "serde_json",
    version = "1.0.143"
)

crate.spec(
    package = "slotmap",
    version = "1.0.7",
    features = ["serde"]
)

crate.spec(
    package = "serde",
    version = "1.0.228",
    features = ["derive"],
)

crate.spec(
    package = "ciborium",
    version = "0.2.2"
)

crate.from_specs()
use_repo(crate, "crates")
