#!/bin/bash

# Ensure we exit immediately if any command fails
set -e

# The Jsonnet files are passed via the 'data' attribute in BUILD.bazel.
# They are available in the runfiles tree. We look for them relative to the
# workspace root. The Bazel workspace path is provided by the first environment variable.

# Find the Bazel runfiles root
RUNFILES_DIR="$(pwd)"

# 1. Define the path to the interpreter (the :main target)
# The :main binary is a dependency, so it's in the runfiles.
# $0 is the path to this script, test_runner.sh
JSONNET_INTERPRETER_PATH="$RUNFILES_DIR/main"

if [ ! -f "$JSONNET_INTERPRETER_PATH" ]; then
    echo "ERROR: Jsonnet interpreter (:main) not found at $JSONNET_INTERPRETER_PATH" >&2
    printenv
    exit 1
fi

ALL_PASS=true

# 2. Iterate over the input files
# We expect the list of files to be provided as arguments to this script.
# In a real Bazel test, you usually rely on environment variables or specific
# file lists if they were generated by a rule.
# For simplicity here, we assume the list of files is implicitly available
# and we will iterate over them using a predefined list.

# For this shell script test, we need a robust way to list the files passed in `data`.
# Since Bazel's `sh_test` doesn't pass the list of `data` files as arguments
# automatically, we rely on the knowledge of what was globbed and how runfiles
# structure the output.

# We know we globbed files from the current directory, so we search the
# runfiles structure for them relative to the workspace path.

echo "Searching runfiles for *.jsonnet files..."
# The files are located in the runfiles directory under the workspace name.
JSONNET_FILES=$(find "$RUNFILES_DIR/end2end/" -name "*.jsonnet" | sort)

if [ -z "$JSONNET_FILES" ]; then
    echo "WARNING: No .jsonnet files found to test."
    exit 0
fi

echo "Found Jsonnet files:"
echo "$JSONNET_FILES"

for jsonnet_file in $JSONNET_FILES; do
    # Pass the absolute path to the Jsonnet tool
    if ! "$JSONNET_INTERPRETER_PATH" "$jsonnet_file"; then
        if ! [[ "$jsonnet_file" == *"wrong"* || "$jsonnet_file" == *"unmatched"* || "$jsonnet_file" == *"error"*  || "$jsonnet_file" == *"unexpected"* || "$jsonnet_file" == *"missing"* ]]; then
            echo "!!! TEST FAILED for $jsonnet_file !!!" >&2
            ALL_PASS=false
        else
            echo "--- TEST PASSED for $jsonnet_file ---"
        fi
    else
        if [[ "$jsonnet_file" == *"wrong"* || "$jsonnet_file" == *"unmatched"* || "$jsonnet_file" == *"error"*  || "$jsonnet_file" == *"unexpected"* || "$jsonnet_file" == *"missing"* ]]; then
            echo "!!! TEST FAILED for $jsonnet_file !!!" >&2
            ALL_PASS=false
        else
            echo "--- TEST PASSED for $jsonnet_file ---"
        fi
    fi
    echo ""
done

if [ "$ALL_PASS" = true ]; then
    echo "All Jsonnet files passed validation."
    exit 0
else
    echo "One or more Jsonnet files failed validation." >&2
    exit 1
fi
