load("@rules_shell//shell:sh_test.bzl", "sh_test")
load("//rules:jsonnet.bzl", "jsonnet_test", "jsonnet_library")

JSONNET_FILES = glob(["*.jsonnet"], exclude = ["*_framework_test.jsonnet", "test_runner_*.jsonnet"])
DATA_FILES = glob(["*.libsonnet", "*.txt", "*.bin"])

[
    sh_test(
        name = f.replace(".jsonnet", "_test"),
        srcs = ["run_test.sh"],
        args = [
            "$(location //:main_stress)",
            "$(location %s)" % f,
        ],
        data = [
            "//:main_stress",
            f,
        ] + DATA_FILES,
    )
    for f in JSONNET_FILES
]

jsonnet_library(
    name = "integration_lib",
    src = "import_integration_test.libsonnet",
)

jsonnet_test(
    name = "test_framework_integration_test",
    src = "test_framework_test.jsonnet",
    coverage = "lcov",
    deps = [
        ":integration_lib",
    ],
)

jsonnet_test(
    name = "test_filter_framework_integration_test",
    src = "test_filter_framework_test.jsonnet",
    coverage = "lcov",
)

sh_test(
    name = "test_runner_failing_integration_test",
    srcs = ["run_failing_test.sh"],
    args = [
        "$(location //:jsonnet_test_runner)",
        "$(location test_runner_failing_test.jsonnet)",
    ],
    data = [
        "//:jsonnet_test_runner",
        "test_runner_failing_test.jsonnet",
    ],
)

sh_test(
    name = "lcov_coverage_integration_test",
    srcs = ["run_lcov_coverage_test.sh"],
    args = [
        "$(location //:jsonnet_test_runner)",
        "$(location test_framework_test.jsonnet)",
    ],
    data = [
        "//:jsonnet_test_runner",
        "test_framework_test.jsonnet",
        "import_integration_test.libsonnet",
    ],
)
