load("@rules_shell//shell:sh_test.bzl", "sh_test")
load(":test_manifest.bzl", "TESTS")

# Support files from the official Jsonnet test suite.
SUPPORT_FILES = ["@jsonnet_test_suite_source//:support_files"]

[
    sh_test(
        name = name + "_test",
        srcs = ["run_test.sh"],
        args = [
            "$(location //:main)",
            "$(location @jsonnet_test_suite_source//:test_suite/%s.jsonnet)" % name,
        ] + (["$(location @jsonnet_test_suite_source//:test_suite/%s.jsonnet.golden)" % name] if has_golden else []),
        data = [
            "//:main",
            "@jsonnet_test_suite_source//:test_suite/%s.jsonnet" % name,
        ] + (["@jsonnet_test_suite_source//:test_suite/%s.jsonnet.golden" % name] if has_golden else []) + SUPPORT_FILES,
    )
    for name, has_golden in TESTS
]
