load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_test(
    name = "benchmark_test",
    size = "large",
    srcs = ["run_benchmarks.sh"],
    args = [
        "$(location @hyperfine_bin//:hyperfine)",
        "$(location //:main)",
        "$(locations @jsonnet_test_suite_source//:benchmarks)",
    ],
    data = [
        "//:main",
        "@jsonnet_test_suite_source//:benchmarks",
        "@hyperfine_bin//:hyperfine",
    ],
)
