load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

filegroup(
    name = "extra_benchmarks",
    srcs = glob(["extra/*.jsonnet"]),
)

sh_binary(
    name = "benchmark",
    srcs = ["run_benchmarks.sh"],
    args = [
        "$(location @hyperfine_bin//:hyperfine)",
        "$(location //:main)",
        "$(locations @jsonnet_test_suite_source//:benchmarks)",
        "$(locations //benchmarks:extra_benchmarks)",
    ],
    data = [
        "//:main",
        "@jsonnet_test_suite_source//:benchmarks",
        "//benchmarks:extra_benchmarks",
        "@hyperfine_bin//:hyperfine",
    ],
)
